'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace HtmlEditorCustomFontDialog.UserControls


	''' <summary>
	''' CustomFontDialog class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class CustomFontDialog

		''' <summary>
		''' pcCustomFontDialog control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pcCustomFontDialog As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

		''' <summary>
		''' hf control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected hf As Global.DevExpress.Web.ASPxHiddenField.ASPxHiddenField

		''' <summary>
		''' cmbFontName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cmbFontName As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

		''' <summary>
		''' spnFontSize control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected spnFontSize As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

		''' <summary>
		''' clrFontColor control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected clrFontColor As Global.DevExpress.Web.ASPxEditors.ASPxColorEdit

		''' <summary>
		''' btnOK control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnOK As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' btnCancel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton
	End Class
End Namespace
